import { unique } from "next/dist/build/utils";
import {
  bytesToDataString,
  cleanPlanName,
  EAIspopular,
  isEAPlanReloadable,
  parseActivationType,
  parseBoolean,
  parseCountryCodes,
  parseEAPlanType,
  parseDataValue,
  parseReducedSpeed,
  parseRequiredInt,
  parseStringList,
  requireString,
  WMIsPopular,
  generateWMUniqueName,
  generateEAUniqueName,
} from "./parsers";

export const supplierToDBFuncMap = {
  WM: {
    productId: (row) => requireString(row["wmproductId"]),
    code: (row) => requireString(row["Code"]),
    name: (row) => cleanPlanName(row["plan name"]),
    days: (row) => parseRequiredInt(row["Days"]),
    limited: (row) => parseDataValue("GB", row["GB"]).greaterThan(0),
    fup: (row) => requireString(row["GB"]),
    data: (row) => parseDataValue("GB", row["GB"]),
    dailyDataCap: (row) => row["GB per day"] ?? null,
    reducedSpeed: (row) => parseReducedSpeed(row["reduced speed"]),
    price: (row) => parseRequiredInt(row["Sell Price"]), // stored in cents
    reloadable: (row) => parseBoolean(row["Reloadable"]),
    countryCodes: (row) => parseCountryCodes(row["Country code"]),
    networks: (row) => parseStringList(row["Networks"]),
    networkSpeed: (row) => row["Network Speed"] ?? null,
    apn: (row) => row["APN"] ?? null,
    hotspot: (row) => parseBoolean(row["Hotspot"]) ?? null,
    activation: (row) => row["Activation"] ?? null,
    delivery: (row) => row["Delivery"] ?? null,
    seoText: (row) => row["Your Plan Summary"] ?? null,
    planType: (row) => row["Plan Type"] ?? null,
    localNumber: (row) => row["Local Number"] ?? null,
    eKYC: () => null,
    uniqueName: (row) => generateWMUniqueName(row),
    isPopular: (row) => WMIsPopular(row),
    supplier: () => "WM",
  },

  EA: {
    productId: (row) => requireString(row.packageCode),
    code: (row) => requireString(row.slug),
    name: (row) => cleanPlanName(row.name),
    days: (row) => parseRequiredInt(row.duration),
    limited: (row) =>
      parseDataValue(bytesToDataString(row.volume)).greaterThan(0),
    fup: (row) => bytesToDataString(row.volume),
    data: (row) => parseDataValue(bytesToDataString(row.volume)),
    dailyDataCap: () => null,
    reducedSpeed: (row) => parseReducedSpeed(row.fupPolicy),
    price: (row) => parseRequiredInt(row["Price in cents"]), // stored in cents
    reloadable: (row) => isEAPlanReloadable(row.supportTopUpType),
    countryCodes: (row) => parseCountryCodes(row.resolvedCountryCodes),
    networks: (row) => parseStringList(row.locationNetworkList),
    networkSpeed: (row) => row.speed ?? null,
    apn: () => null,
    hotspot: () => null,
    activation: (row) => parseActivationType(row.activeType) ?? null,
    delivery: () => null,
    seoText: (row) => row.description ?? null,
    planType: (row) => parseEAPlanType(row.dataType, row.smsStatus) ?? null,
    localNumber: () => null,
    eKYC: () => null,
    uniqueName: (row) => generateEAUniqueName(row),
    isPopular: () => EAIspopular(),
    supplier: () => "EA",
  },
};
